### PR TITLE
read lines

### PR DESCRIPTION
**Pull request by JKap56**
-Moved conversions to new "converter function"
-stored original latexToPretext as a comment
-New exported latexToPretext attempts to read selection by lines to determine conversions/build paragraphs

This version still has known issue of formatting every line of text as a paragraph not just lines separated by empty lines.  Wanted to start up/test out the workflow of communicating through github as per our previous meeting

### CODE REVIEW

**Comment by oscarlevin** [comment]
I've figured out how to checkout a pr locally and make edits.  So we can keep going now.

I've played around a bit testing the current code out.  It looks like I am missing a closing `</p>` tag on at the end of a selection.  What if we try to have a function that parses the selected text and returns a list of paragraphs, each of which will be wrapped in a `<p>` element?  I need to look closer to see what you are currently doing, but perhaps you can try to isolate this logic in its own function which will make it easier for me to inspect.

**Comment by JKap56** [comment]
Am I remembering correctly that lines of text within areas that should not be converted, should still be formatted within <p> </p>.  For instance text within \begin{tikzpicture}...\end{tikzpicture}?  I wouldn't convert inline math from $..$ to <m></m>, but should begin/end paragraphs be added within that area?

**Comment by oscarlevin** [comment]
I think `\begin{tikzpicture}` is special.  Something like `\begin{theorem}` should be converted to `<theorem>\n<statement>` and then have it's text content wrapped in `<p>` tags and further converted below that.

We should eventually also handle `\begin{itemize}` to make `<ul>`, which each `\item` being a `<li>`, and its text content wrapped in `<p>`.

**Comment by oscarlevin** [comment]
This is fantastic.

**Pull request merged**
